apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: ml-nutrition-pipeline # le nom de notre cluster
  region: us-east-1 # la région, à modifier si besoin
  version: "1.33" # la version de kubernetes utilisée

iam:
  withOIDC: true # OICD = OpenID Connect ->eksctl create cluster -f cluster.yaml  sécurise le cluster
  serviceRoleARN: arn:aws:iam::609103576748:role/eksClusterRole # iam de 12 chiffres à modifier

managedNodeGroups: # caractéristiques des machines qui vont tourner
  - name: ng-on-demand
    instanceTypes: [t3.small] # type de machine 
    desiredCapacity: 1 # on lance une seule machine (limite les coûts)